-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity log_2_64bit is
port (
    ap_ready : OUT STD_LOGIC;
    tmp_V : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of log_2_64bit is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv16_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv16_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv16_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv16_20 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv16_40 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv16_80 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv16_100 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv16_200 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv16_400 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv16_800 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv16_1000 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv16_2000 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv16_4000 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv6_26 : STD_LOGIC_VECTOR (5 downto 0) := "100110";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv6_2C : STD_LOGIC_VECTOR (5 downto 0) := "101100";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_2E : STD_LOGIC_VECTOR (5 downto 0) := "101110";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_phi_mux_p_s_phi_fu_159_p34 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal AA_V_fu_380_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_p_1_phi_fu_215_p34 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal BB_V_fu_384_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_p_2_phi_fu_271_p34 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal CC_V_fu_394_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_p_3_phi_fu_327_p34 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_3_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal DD_V_fu_404_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_3_cast2_fu_450_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_1_cast_fu_430_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_cast_fu_420_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_458_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_2_cast_fu_440_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_3_cast_fu_454_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp1_fu_468_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp1_cast_fu_474_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_cast_fu_464_p1 : STD_LOGIC_VECTOR (7 downto 0);


begin



    AA_V_fu_380_p1 <= tmp_V(16 - 1 downto 0);
    BB_V_fu_384_p4 <= tmp_V(31 downto 16);
    CC_V_fu_394_p4 <= tmp_V(47 downto 32);
    DD_V_fu_404_p4 <= tmp_V(63 downto 48);

    ap_phi_mux_p_1_phi_fu_215_p34_assign_proc : process(tmp_4_fu_424_p2, BB_V_fu_384_p4)
    begin
        if ((tmp_4_fu_424_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_0;
        elsif ((not((ap_const_lv16_8000 = BB_V_fu_384_p4)) and not((ap_const_lv16_4000 = BB_V_fu_384_p4)) and not((ap_const_lv16_2000 = BB_V_fu_384_p4)) and not((ap_const_lv16_1000 = BB_V_fu_384_p4)) and not((ap_const_lv16_800 = BB_V_fu_384_p4)) and not((ap_const_lv16_400 = BB_V_fu_384_p4)) and not((ap_const_lv16_200 = BB_V_fu_384_p4)) and not((ap_const_lv16_100 = BB_V_fu_384_p4)) and not((ap_const_lv16_80 = BB_V_fu_384_p4)) and not((ap_const_lv16_40 = BB_V_fu_384_p4)) and not((ap_const_lv16_20 = BB_V_fu_384_p4)) and not((ap_const_lv16_10 = BB_V_fu_384_p4)) and not((ap_const_lv16_8 = BB_V_fu_384_p4)) and not((ap_const_lv16_4 = BB_V_fu_384_p4)) and not((ap_const_lv16_2 = BB_V_fu_384_p4)) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_10;
        elsif (((ap_const_lv16_8000 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_1F;
        elsif (((ap_const_lv16_4000 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_1E;
        elsif (((ap_const_lv16_2000 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_1D;
        elsif (((ap_const_lv16_1000 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_1C;
        elsif (((ap_const_lv16_800 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_1B;
        elsif (((ap_const_lv16_400 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_1A;
        elsif (((ap_const_lv16_200 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_19;
        elsif (((ap_const_lv16_100 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_18;
        elsif (((ap_const_lv16_80 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_17;
        elsif (((ap_const_lv16_40 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_16;
        elsif (((ap_const_lv16_20 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_15;
        elsif (((ap_const_lv16_10 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_14;
        elsif (((ap_const_lv16_8 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_13;
        elsif (((ap_const_lv16_4 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_12;
        elsif (((ap_const_lv16_2 = BB_V_fu_384_p4) and (tmp_4_fu_424_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_1_phi_fu_215_p34 <= ap_const_lv5_11;
        else 
            ap_phi_mux_p_1_phi_fu_215_p34 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_p_2_phi_fu_271_p34_assign_proc : process(tmp_8_fu_434_p2, CC_V_fu_394_p4)
    begin
        if ((tmp_8_fu_434_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_0;
        elsif ((not((ap_const_lv16_8000 = CC_V_fu_394_p4)) and not((ap_const_lv16_4000 = CC_V_fu_394_p4)) and not((ap_const_lv16_2000 = CC_V_fu_394_p4)) and not((ap_const_lv16_1000 = CC_V_fu_394_p4)) and not((ap_const_lv16_800 = CC_V_fu_394_p4)) and not((ap_const_lv16_400 = CC_V_fu_394_p4)) and not((ap_const_lv16_200 = CC_V_fu_394_p4)) and not((ap_const_lv16_100 = CC_V_fu_394_p4)) and not((ap_const_lv16_80 = CC_V_fu_394_p4)) and not((ap_const_lv16_40 = CC_V_fu_394_p4)) and not((ap_const_lv16_20 = CC_V_fu_394_p4)) and not((ap_const_lv16_10 = CC_V_fu_394_p4)) and not((ap_const_lv16_8 = CC_V_fu_394_p4)) and not((ap_const_lv16_4 = CC_V_fu_394_p4)) and not((ap_const_lv16_2 = CC_V_fu_394_p4)) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_20;
        elsif (((ap_const_lv16_8000 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_2F;
        elsif (((ap_const_lv16_4000 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_2E;
        elsif (((ap_const_lv16_2000 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_2D;
        elsif (((ap_const_lv16_1000 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_2C;
        elsif (((ap_const_lv16_800 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_2B;
        elsif (((ap_const_lv16_400 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_2A;
        elsif (((ap_const_lv16_200 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_29;
        elsif (((ap_const_lv16_100 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_28;
        elsif (((ap_const_lv16_80 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_27;
        elsif (((ap_const_lv16_40 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_26;
        elsif (((ap_const_lv16_20 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_25;
        elsif (((ap_const_lv16_10 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_24;
        elsif (((ap_const_lv16_8 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_23;
        elsif (((ap_const_lv16_4 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_22;
        elsif (((ap_const_lv16_2 = CC_V_fu_394_p4) and (tmp_8_fu_434_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_2_phi_fu_271_p34 <= ap_const_lv6_21;
        else 
            ap_phi_mux_p_2_phi_fu_271_p34 <= "XXXXXX";
        end if; 
    end process;


    ap_phi_mux_p_3_phi_fu_327_p34_assign_proc : process(tmp_3_fu_444_p2, DD_V_fu_404_p4)
    begin
        if ((tmp_3_fu_444_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_0;
        elsif ((not((ap_const_lv16_8000 = DD_V_fu_404_p4)) and not((ap_const_lv16_4000 = DD_V_fu_404_p4)) and not((ap_const_lv16_2000 = DD_V_fu_404_p4)) and not((ap_const_lv16_1000 = DD_V_fu_404_p4)) and not((ap_const_lv16_800 = DD_V_fu_404_p4)) and not((ap_const_lv16_400 = DD_V_fu_404_p4)) and not((ap_const_lv16_200 = DD_V_fu_404_p4)) and not((ap_const_lv16_100 = DD_V_fu_404_p4)) and not((ap_const_lv16_80 = DD_V_fu_404_p4)) and not((ap_const_lv16_40 = DD_V_fu_404_p4)) and not((ap_const_lv16_20 = DD_V_fu_404_p4)) and not((ap_const_lv16_10 = DD_V_fu_404_p4)) and not((ap_const_lv16_8 = DD_V_fu_404_p4)) and not((ap_const_lv16_4 = DD_V_fu_404_p4)) and not((ap_const_lv16_2 = DD_V_fu_404_p4)) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_10;
        elsif (((ap_const_lv16_8000 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_1F;
        elsif (((ap_const_lv16_4000 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_1E;
        elsif (((ap_const_lv16_2000 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_1D;
        elsif (((ap_const_lv16_1000 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_1C;
        elsif (((ap_const_lv16_800 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_1B;
        elsif (((ap_const_lv16_400 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_1A;
        elsif (((ap_const_lv16_200 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_19;
        elsif (((ap_const_lv16_100 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_18;
        elsif (((ap_const_lv16_80 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_17;
        elsif (((ap_const_lv16_40 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_16;
        elsif (((ap_const_lv16_20 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_15;
        elsif (((ap_const_lv16_10 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_14;
        elsif (((ap_const_lv16_8 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_13;
        elsif (((ap_const_lv16_4 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_12;
        elsif (((ap_const_lv16_2 = DD_V_fu_404_p4) and (tmp_3_fu_444_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_3_phi_fu_327_p34 <= ap_const_lv5_11;
        else 
            ap_phi_mux_p_3_phi_fu_327_p34 <= "XXXXX";
        end if; 
    end process;


    ap_phi_mux_p_s_phi_fu_159_p34_assign_proc : process(tmp_1_fu_414_p2, AA_V_fu_380_p1)
    begin
        if (((tmp_1_fu_414_p2 = ap_const_lv1_1) or (not((ap_const_lv16_8000 = AA_V_fu_380_p1)) and not((ap_const_lv16_4000 = AA_V_fu_380_p1)) and not((ap_const_lv16_2000 = AA_V_fu_380_p1)) and not((ap_const_lv16_1000 = AA_V_fu_380_p1)) and not((ap_const_lv16_800 = AA_V_fu_380_p1)) and not((ap_const_lv16_400 = AA_V_fu_380_p1)) and not((ap_const_lv16_200 = AA_V_fu_380_p1)) and not((ap_const_lv16_100 = AA_V_fu_380_p1)) and not((ap_const_lv16_80 = AA_V_fu_380_p1)) and not((ap_const_lv16_40 = AA_V_fu_380_p1)) and not((ap_const_lv16_20 = AA_V_fu_380_p1)) and not((ap_const_lv16_10 = AA_V_fu_380_p1)) and not((ap_const_lv16_8 = AA_V_fu_380_p1)) and not((ap_const_lv16_4 = AA_V_fu_380_p1)) and not((ap_const_lv16_2 = AA_V_fu_380_p1)) and (tmp_1_fu_414_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_0;
        elsif (((ap_const_lv16_8000 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_F;
        elsif (((ap_const_lv16_4000 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_E;
        elsif (((ap_const_lv16_2000 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_D;
        elsif (((ap_const_lv16_1000 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_C;
        elsif (((ap_const_lv16_800 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_B;
        elsif (((ap_const_lv16_400 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_A;
        elsif (((ap_const_lv16_200 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_9;
        elsif (((ap_const_lv16_100 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_8;
        elsif (((ap_const_lv16_80 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_7;
        elsif (((ap_const_lv16_40 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_6;
        elsif (((ap_const_lv16_20 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_5;
        elsif (((ap_const_lv16_10 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_4;
        elsif (((ap_const_lv16_8 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_3;
        elsif (((ap_const_lv16_4 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_2;
        elsif (((ap_const_lv16_2 = AA_V_fu_380_p1) and (tmp_1_fu_414_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_p_s_phi_fu_159_p34 <= ap_const_lv4_1;
        else 
            ap_phi_mux_p_s_phi_fu_159_p34 <= "XXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(tmp1_cast_fu_474_p1) + unsigned(tmp_cast_fu_464_p1));
    p_1_cast_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_p_1_phi_fu_215_p34),6));
    p_2_cast_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_p_2_phi_fu_271_p34),7));
        p_3_cast2_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_phi_mux_p_3_phi_fu_327_p34),6));

    p_3_cast_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_3_cast2_fu_450_p1),7));
    p_cast_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_p_s_phi_fu_159_p34),6));
    tmp1_cast_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_468_p2),8));
    tmp1_fu_468_p2 <= std_logic_vector(unsigned(p_2_cast_fu_440_p1) + unsigned(p_3_cast_fu_454_p1));
    tmp_1_fu_414_p2 <= "1" when (AA_V_fu_380_p1 = ap_const_lv16_0) else "0";
    tmp_3_fu_444_p2 <= "1" when (DD_V_fu_404_p4 = ap_const_lv16_0) else "0";
    tmp_4_fu_424_p2 <= "1" when (BB_V_fu_384_p4 = ap_const_lv16_0) else "0";
    tmp_8_fu_434_p2 <= "1" when (CC_V_fu_394_p4 = ap_const_lv16_0) else "0";
    tmp_cast_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_458_p2),8));
    tmp_fu_458_p2 <= std_logic_vector(unsigned(p_1_cast_fu_430_p1) + unsigned(p_cast_fu_420_p1));
end behav;
