# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HTA_theta_0_0/design_1_HTA_theta_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_HTA_theta_0_0 || ORIG_REF_NAME==design_1_HTA_theta_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_0 || ORIG_REF_NAME==design_1_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HLS_MAXHEAP_HTA_0_1/design_1_HLS_MAXHEAP_HTA_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_HLS_MAXHEAP_HTA_0_1 || ORIG_REF_NAME==design_1_HLS_MAXHEAP_HTA_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1 || ORIG_REF_NAME==design_1_clk_wiz_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_100M_1/design_1_rst_clk_wiz_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_100M_1 || ORIG_REF_NAME==design_1_rst_clk_wiz_100M_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
