// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __acc16kmau_req_list_H__
#define __acc16kmau_req_list_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct acc16kmau_req_list_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 14;
  static const unsigned AddressRange = 1024;
  static const unsigned AddressWidth = 10;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(acc16kmau_req_list_ram) {
        ram[0] = "0b00000000000011";
        ram[1] = "0b00000000001100";
        ram[2] = "0b00000000000010";
        ram[3] = "0b00000000000001";
        ram[4] = "0b00000000000001";
        ram[5] = "0b00000000000001";
        ram[6] = "0b00000000001000";
        ram[7] = "0b00000000000011";
        ram[8] = "0b00000000000011";
        ram[9] = "0b00000000001101";
        ram[10] = "0b00000000001101";
        ram[11] = "0b00000000001111";
        ram[12] = "0b00000000000111";
        ram[13] = "0b00000000000101";
        ram[14] = "0b00000000001011";
        ram[15] = "0b00000000000111";
        ram[16] = "0b00000000010000";
        ram[17] = "0b00000000010000";
        ram[18] = "0b00000000000001";
        ram[19] = "0b00000000000001";
        ram[20] = "0b00000000000011";
        ram[21] = "0b00000000000011";
        ram[22] = "0b00000000000101";
        ram[23] = "0b00000000000101";
        ram[24] = "0b00000000000010";
        ram[25] = "0b00000000000101";
        ram[26] = "0b00000000000100";
        ram[27] = "0b00000000010000";
        ram[28] = "0b00000001110000";
        ram[29] = "0b00000000000111";
        ram[30] = "0b00000000000011";
        ram[31] = "0b00000000010000";
        ram[32] = "0b00000000010000";
        ram[33] = "0b00000000010000";
        ram[34] = "0b00000000000101";
        ram[35] = "0b00000000000101";
        ram[36] = "0b00000000000101";
        ram[37] = "0b00000000001100";
        ram[38] = "0b00000000110000";
        ram[39] = "0b00000001101000";
        ram[40] = "0b00000010010000";
        ram[41] = "0b00000000000011";
        ram[42] = "0b00000000001101";
        ram[43] = "0b00000000001100";
        ram[44] = "0b00000000000100";
        ram[45] = "0b00000000001001";
        ram[46] = "0b00000000000111";
        ram[47] = "0b00000000000100";
        ram[48] = "0b00000000000111";
        ram[49] = "0b00000001101011";
        ram[50] = "0b00000011000110";
        ram[51] = "0b00000000000011";
        ram[52] = "0b00000010000000";
        ram[53] = "0b00000010011010";
        ram[54] = "0b00100000011111";
        ram[55] = "0b00000000001010";
        ram[56] = "0b00000000000100";
        ram[57] = "0b00000000001010";
        ram[58] = "0b00000000110111";
        ram[59] = "0b01000001010100";
        ram[60] = "0b00000000001010";
        ram[61] = "0b00000010111000";
        ram[62] = "0b00000000000011";
        ram[63] = "0b00000000000100";
        ram[64] = "0b00000100000111";
        ram[65] = "0b00010000100001";
        ram[66] = "0b00000101100111";
        ram[67] = "0b00000000001000";
        ram[68] = "0b00000000000001";
        ram[69] = "0b00000000001010";
        ram[70] = "0b00000000110000";
        ram[71] = "0b00000000001101";
        ram[72] = "0b00000011111000";
        ram[73] = "0b00000000000010";
        ram[74] = "0b00000000001100";
        ram[75] = "0b00000000000111";
        ram[76] = "0b00000001110000";
        ram[77] = "0b00000000001000";
        ram[78] = "0b00000000000100";
        ram[79] = "0b00000001000000";
        ram[80] = "0b00000011010000";
        ram[81] = "0b00000000000101";
        ram[82] = "0b00000000000110";
        ram[83] = "0b00000000001001";
        ram[84] = "0b00000000000101";
        ram[85] = "0b00000011010000";
        ram[86] = "0b10000000000000";
        ram[87] = "0b01000000011011";
        ram[88] = "0b00000000001001";
        ram[89] = "0b00000000001010";
        ram[90] = "0b00000010000000";
        ram[91] = "0b00000000000011";
        ram[92] = "0b00000000000111";
        ram[93] = "0b00001000000000";
        ram[94] = "0b00000010000111";
        ram[95] = "0b00000000001010";
        ram[96] = "0b00000010000000";
        ram[97] = "0b00000000000011";
        ram[98] = "0b00000000000011";
        ram[99] = "0b00100000000000";
        for (unsigned i = 100; i < 1024 ; i = i + 1) {
            ram[i] = "0b00000000000000";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(acc16kmau_req_list) {


static const unsigned DataWidth = 14;
static const unsigned AddressRange = 1024;
static const unsigned AddressWidth = 10;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


acc16kmau_req_list_ram* meminst;


SC_CTOR(acc16kmau_req_list) {
meminst = new acc16kmau_req_list_ram("acc16kmau_req_list_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~acc16kmau_req_list() {
    delete meminst;
}


};//endmodule
#endif
