// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __acc16kmau_req_cmd_H__
#define __acc16kmau_req_cmd_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct acc16kmau_req_cmd_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 2;
  static const unsigned AddressRange = 1024;
  static const unsigned AddressWidth = 10;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(acc16kmau_req_cmd_ram) {
        for (unsigned i = 0; i < 27 ; i = i + 1) {
            ram[i] = "0b10";
        }
        ram[27] = "0b11";
        ram[28] = "0b11";
        ram[29] = "0b11";
        for (unsigned i = 30; i < 37 ; i = i + 1) {
            ram[i] = "0b10";
        }
        ram[37] = "0b11";
        ram[38] = "0b11";
        ram[39] = "0b11";
        ram[40] = "0b11";
        for (unsigned i = 41; i < 47 ; i = i + 1) {
            ram[i] = "0b10";
        }
        ram[47] = "0b11";
        ram[48] = "0b11";
        ram[49] = "0b10";
        ram[50] = "0b10";
        ram[51] = "0b10";
        ram[52] = "0b11";
        ram[53] = "0b10";
        ram[54] = "0b10";
        ram[55] = "0b11";
        ram[56] = "0b10";
        ram[57] = "0b10";
        ram[58] = "0b10";
        ram[59] = "0b10";
        ram[60] = "0b11";
        ram[61] = "0b11";
        for (unsigned i = 62; i < 70 ; i = i + 1) {
            ram[i] = "0b10";
        }
        ram[70] = "0b11";
        ram[71] = "0b10";
        ram[72] = "0b11";
        ram[73] = "0b10";
        ram[74] = "0b11";
        ram[75] = "0b10";
        ram[76] = "0b11";
        ram[77] = "0b11";
        ram[78] = "0b10";
        ram[79] = "0b11";
        ram[80] = "0b11";
        ram[81] = "0b10";
        ram[82] = "0b10";
        ram[83] = "0b10";
        ram[84] = "0b10";
        ram[85] = "0b11";
        ram[86] = "0b11";
        ram[87] = "0b10";
        ram[88] = "0b11";
        ram[89] = "0b10";
        ram[90] = "0b11";
        ram[91] = "0b10";
        ram[92] = "0b10";
        ram[93] = "0b11";
        ram[94] = "0b10";
        ram[95] = "0b11";
        ram[96] = "0b11";
        ram[97] = "0b10";
        ram[98] = "0b10";
        ram[99] = "0b11";
        for (unsigned i = 100; i < 1024 ; i = i + 1) {
            ram[i] = "0b00";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(acc16kmau_req_cmd) {


static const unsigned DataWidth = 2;
static const unsigned AddressRange = 1024;
static const unsigned AddressWidth = 10;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


acc16kmau_req_cmd_ram* meminst;


SC_CTOR(acc16kmau_req_cmd) {
meminst = new acc16kmau_req_cmd_ram("acc16kmau_req_cmd_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~acc16kmau_req_cmd() {
    delete meminst;
}


};//endmodule
#endif
