// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __Ext_KWTA8k_mark_mhbi_H__
#define __Ext_KWTA8k_mark_mhbi_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct Ext_KWTA8k_mark_mhbi_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 8;
  static const unsigned AddressRange = 128;
  static const unsigned AddressWidth = 7;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(Ext_KWTA8k_mark_mhbi_ram) {
        ram[0] = "0b11001101";
        ram[1] = "0b00110010";
        ram[2] = "0b11000101";
        ram[3] = "0b00001001";
        ram[4] = "0b00010010";
        ram[5] = "0b00100010";
        ram[6] = "0b01000101";
        ram[7] = "0b10000101";
        ram[8] = "0b00001001";
        ram[9] = "0b00001001";
        ram[10] = "0b00010010";
        ram[11] = "0b00010010";
        ram[12] = "0b00100010";
        ram[13] = "0b00100010";
        ram[14] = "0b01000101";
        ram[15] = "0b01000101";
        ram[16] = "0b10000101";
        ram[17] = "0b10000101";
        ram[18] = "0b00001001";
        ram[19] = "0b00001001";
        ram[20] = "0b00001001";
        ram[21] = "0b00001001";
        ram[22] = "0b00010010";
        ram[23] = "0b00010010";
        ram[24] = "0b00010010";
        ram[25] = "0b00010010";
        ram[26] = "0b00100010";
        ram[27] = "0b00100010";
        ram[28] = "0b00100010";
        ram[29] = "0b00100010";
        ram[30] = "0b01000101";
        ram[31] = "0b01000101";
        ram[32] = "0b01000101";
        ram[33] = "0b01000101";
        ram[34] = "0b10000101";
        ram[35] = "0b10000101";
        ram[36] = "0b10000101";
        ram[37] = "0b10000101";
        for (unsigned i = 38; i < 46 ; i = i + 1) {
            ram[i] = "0b00001001";
        }
        for (unsigned i = 46; i < 54 ; i = i + 1) {
            ram[i] = "0b00010010";
        }
        for (unsigned i = 54; i < 62 ; i = i + 1) {
            ram[i] = "0b00100010";
        }
        ram[62] = "0b11001101";
        ram[63] = "0b00110010";
        ram[64] = "0b11000100";
        ram[65] = "0b00001000";
        ram[66] = "0b00010000";
        ram[67] = "0b00100000";
        ram[68] = "0b01000000";
        ram[69] = "0b10000000";
        for (unsigned i = 70; i < 128 ; i = i + 1) {
            ram[i] = "0b00000000";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(Ext_KWTA8k_mark_mhbi) {


static const unsigned DataWidth = 8;
static const unsigned AddressRange = 128;
static const unsigned AddressWidth = 7;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


Ext_KWTA8k_mark_mhbi_ram* meminst;


SC_CTOR(Ext_KWTA8k_mark_mhbi) {
meminst = new Ext_KWTA8k_mark_mhbi_ram("Ext_KWTA8k_mark_mhbi_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~Ext_KWTA8k_mark_mhbi() {
    delete meminst;
}


};//endmodule
#endif
