webtalk_init -webtalk_dir /home/tingyuan/Temporary/vivado-outputs/Algorithm_MAXHEAP_HTA/Algorithm_MAXHEAP_HTA.sim/sim_1/impl/timing/xsim/xsim.dir/design_1_wrapper_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 28 21:58:53 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210387038_174145948_210294029_823" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1893319e-796d-4d1b-8ad5-20482a058896" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ebdbaca18c7e49ef9613f8c324318111" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1655.669 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "302500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "416.07_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "341160_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2125370280 -regid "210387038_174145948_210294029_823" -xml /home/tingyuan/Temporary/vivado-outputs/Algorithm_MAXHEAP_HTA/Algorithm_MAXHEAP_HTA.sim/sim_1/impl/timing/xsim/xsim.dir/design_1_wrapper_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /home/tingyuan/Temporary/vivado-outputs/Algorithm_MAXHEAP_HTA/Algorithm_MAXHEAP_HTA.sim/sim_1/impl/timing/xsim/xsim.dir/design_1_wrapper_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /home/tingyuan/Temporary/vivado-outputs/Algorithm_MAXHEAP_HTA/Algorithm_MAXHEAP_HTA.sim/sim_1/impl/timing/xsim/xsim.dir/design_1_wrapper_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
