# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: /home/tingyuan/Temporary/vivado-outputs/HTA256_test/HTA256_test.srcs/sources_1/bd/design_1/ip/design_1_HTA2048_theta_0_0/design_1_HTA2048_theta_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_HTA2048_theta_0_0 || ORIG_REF_NAME==design_1_HTA2048_theta_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_acc2048_2048_mau_0_0/design_1_acc2048_2048_mau_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_acc2048_2048_mau_0_0 || ORIG_REF_NAME==design_1_acc2048_2048_mau_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
