// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __HTA512_theta_markjbC_H__
#define __HTA512_theta_markjbC_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct HTA512_theta_markjbC_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 15;
  static const unsigned AddressRange = 32;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(HTA512_theta_markjbC_ram) {
        ram[0] = "0b100001111001101";
        ram[1] = "0b011110000110010";
        ram[2] = "0b100000011000101";
        ram[3] = "0b000001100001001";
        ram[4] = "0b000110000010010";
        ram[5] = "0b011000000100010";
        ram[6] = "0b100000001000101";
        ram[7] = "0b000000010000101";
        ram[8] = "0b000000100001001";
        ram[9] = "0b000001000001001";
        ram[10] = "0b000010000010010";
        ram[11] = "0b000100000010010";
        ram[12] = "0b001000000100010";
        ram[13] = "0b010000000100010";
        ram[14] = "0b100001111001101";
        ram[15] = "0b011110000110010";
        ram[16] = "0b100000011000100";
        ram[17] = "0b000001100001000";
        ram[18] = "0b000110000010000";
        ram[19] = "0b011000000100000";
        ram[20] = "0b100000001000000";
        ram[21] = "0b000000010000000";
        ram[22] = "0b000000100000000";
        ram[23] = "0b000001000000000";
        ram[24] = "0b000010000000000";
        ram[25] = "0b000100000000000";
        ram[26] = "0b001000000000000";
        ram[27] = "0b010000000000000";
        ram[28] = "0b000000000000000";
        ram[29] = "0b000000000000000";
        ram[30] = "0b000000000000000";
        ram[31] = "0b000000000000000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(HTA512_theta_markjbC) {


static const unsigned DataWidth = 15;
static const unsigned AddressRange = 32;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


HTA512_theta_markjbC_ram* meminst;


SC_CTOR(HTA512_theta_markjbC) {
meminst = new HTA512_theta_markjbC_ram("HTA512_theta_markjbC_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~HTA512_theta_markjbC() {
    delete meminst;
}


};//endmodule
#endif
