// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module log_2_64bit (
        ap_ready,
        tmp_V,
        ap_return
);


output   ap_ready;
input  [63:0] tmp_V;
output  [7:0] ap_return;

reg   [3:0] ap_phi_mux_p_s_phi_fu_159_p34;
wire   [0:0] tmp_1_fu_414_p2;
wire   [15:0] AA_V_fu_380_p1;
reg   [4:0] ap_phi_mux_p_1_phi_fu_215_p34;
wire   [0:0] tmp_4_fu_424_p2;
wire   [15:0] BB_V_fu_384_p4;
reg   [5:0] ap_phi_mux_p_2_phi_fu_271_p34;
wire   [0:0] tmp_8_fu_434_p2;
wire   [15:0] CC_V_fu_394_p4;
reg   [4:0] ap_phi_mux_p_3_phi_fu_327_p34;
wire   [0:0] tmp_3_fu_444_p2;
wire   [15:0] DD_V_fu_404_p4;
wire  signed [5:0] p_3_cast2_fu_450_p1;
wire   [5:0] p_1_cast_fu_430_p1;
wire   [5:0] p_cast_fu_420_p1;
wire   [5:0] tmp_fu_458_p2;
wire   [6:0] p_2_cast_fu_440_p1;
wire   [6:0] p_3_cast_fu_454_p1;
wire   [6:0] tmp1_fu_468_p2;
wire   [7:0] tmp1_cast_fu_474_p1;
wire   [7:0] tmp_cast_fu_464_p1;

always @ (*) begin
    if ((tmp_4_fu_424_p2 == 1'd1)) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd0;
    end else if ((~(16'd32768 == BB_V_fu_384_p4) & ~(16'd16384 == BB_V_fu_384_p4) & ~(16'd8192 == BB_V_fu_384_p4) & ~(16'd4096 == BB_V_fu_384_p4) & ~(16'd2048 == BB_V_fu_384_p4) & ~(16'd1024 == BB_V_fu_384_p4) & ~(16'd512 == BB_V_fu_384_p4) & ~(16'd256 == BB_V_fu_384_p4) & ~(16'd128 == BB_V_fu_384_p4) & ~(16'd64 == BB_V_fu_384_p4) & ~(16'd32 == BB_V_fu_384_p4) & ~(16'd16 == BB_V_fu_384_p4) & ~(16'd8 == BB_V_fu_384_p4) & ~(16'd4 == BB_V_fu_384_p4) & ~(16'd2 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd16;
    end else if (((16'd32768 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd31;
    end else if (((16'd16384 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd30;
    end else if (((16'd8192 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd29;
    end else if (((16'd4096 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd28;
    end else if (((16'd2048 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd27;
    end else if (((16'd1024 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd26;
    end else if (((16'd512 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd25;
    end else if (((16'd256 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd24;
    end else if (((16'd128 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd23;
    end else if (((16'd64 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd22;
    end else if (((16'd32 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd21;
    end else if (((16'd16 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd20;
    end else if (((16'd8 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd19;
    end else if (((16'd4 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd18;
    end else if (((16'd2 == BB_V_fu_384_p4) & (tmp_4_fu_424_p2 == 1'd0))) begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 5'd17;
    end else begin
        ap_phi_mux_p_1_phi_fu_215_p34 = 'bx;
    end
end

always @ (*) begin
    if ((tmp_8_fu_434_p2 == 1'd1)) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd0;
    end else if ((~(16'd32768 == CC_V_fu_394_p4) & ~(16'd16384 == CC_V_fu_394_p4) & ~(16'd8192 == CC_V_fu_394_p4) & ~(16'd4096 == CC_V_fu_394_p4) & ~(16'd2048 == CC_V_fu_394_p4) & ~(16'd1024 == CC_V_fu_394_p4) & ~(16'd512 == CC_V_fu_394_p4) & ~(16'd256 == CC_V_fu_394_p4) & ~(16'd128 == CC_V_fu_394_p4) & ~(16'd64 == CC_V_fu_394_p4) & ~(16'd32 == CC_V_fu_394_p4) & ~(16'd16 == CC_V_fu_394_p4) & ~(16'd8 == CC_V_fu_394_p4) & ~(16'd4 == CC_V_fu_394_p4) & ~(16'd2 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd32;
    end else if (((16'd32768 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd47;
    end else if (((16'd16384 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd46;
    end else if (((16'd8192 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd45;
    end else if (((16'd4096 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd44;
    end else if (((16'd2048 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd43;
    end else if (((16'd1024 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd42;
    end else if (((16'd512 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd41;
    end else if (((16'd256 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd40;
    end else if (((16'd128 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd39;
    end else if (((16'd64 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd38;
    end else if (((16'd32 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd37;
    end else if (((16'd16 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd36;
    end else if (((16'd8 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd35;
    end else if (((16'd4 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd34;
    end else if (((16'd2 == CC_V_fu_394_p4) & (tmp_8_fu_434_p2 == 1'd0))) begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 6'd33;
    end else begin
        ap_phi_mux_p_2_phi_fu_271_p34 = 'bx;
    end
end

always @ (*) begin
    if ((tmp_3_fu_444_p2 == 1'd1)) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd0;
    end else if ((~(16'd32768 == DD_V_fu_404_p4) & ~(16'd16384 == DD_V_fu_404_p4) & ~(16'd8192 == DD_V_fu_404_p4) & ~(16'd4096 == DD_V_fu_404_p4) & ~(16'd2048 == DD_V_fu_404_p4) & ~(16'd1024 == DD_V_fu_404_p4) & ~(16'd512 == DD_V_fu_404_p4) & ~(16'd256 == DD_V_fu_404_p4) & ~(16'd128 == DD_V_fu_404_p4) & ~(16'd64 == DD_V_fu_404_p4) & ~(16'd32 == DD_V_fu_404_p4) & ~(16'd16 == DD_V_fu_404_p4) & ~(16'd8 == DD_V_fu_404_p4) & ~(16'd4 == DD_V_fu_404_p4) & ~(16'd2 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd16;
    end else if (((16'd32768 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd31;
    end else if (((16'd16384 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd30;
    end else if (((16'd8192 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd29;
    end else if (((16'd4096 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd28;
    end else if (((16'd2048 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd27;
    end else if (((16'd1024 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd26;
    end else if (((16'd512 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd25;
    end else if (((16'd256 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd24;
    end else if (((16'd128 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd23;
    end else if (((16'd64 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd22;
    end else if (((16'd32 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd21;
    end else if (((16'd16 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd20;
    end else if (((16'd8 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd19;
    end else if (((16'd4 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd18;
    end else if (((16'd2 == DD_V_fu_404_p4) & (tmp_3_fu_444_p2 == 1'd0))) begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 5'd17;
    end else begin
        ap_phi_mux_p_3_phi_fu_327_p34 = 'bx;
    end
end

always @ (*) begin
    if (((tmp_1_fu_414_p2 == 1'd1) | (~(16'd32768 == AA_V_fu_380_p1) & ~(16'd16384 == AA_V_fu_380_p1) & ~(16'd8192 == AA_V_fu_380_p1) & ~(16'd4096 == AA_V_fu_380_p1) & ~(16'd2048 == AA_V_fu_380_p1) & ~(16'd1024 == AA_V_fu_380_p1) & ~(16'd512 == AA_V_fu_380_p1) & ~(16'd256 == AA_V_fu_380_p1) & ~(16'd128 == AA_V_fu_380_p1) & ~(16'd64 == AA_V_fu_380_p1) & ~(16'd32 == AA_V_fu_380_p1) & ~(16'd16 == AA_V_fu_380_p1) & ~(16'd8 == AA_V_fu_380_p1) & ~(16'd4 == AA_V_fu_380_p1) & ~(16'd2 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0)))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd0;
    end else if (((16'd32768 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd15;
    end else if (((16'd16384 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd14;
    end else if (((16'd8192 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd13;
    end else if (((16'd4096 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd12;
    end else if (((16'd2048 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd11;
    end else if (((16'd1024 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd10;
    end else if (((16'd512 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd9;
    end else if (((16'd256 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd8;
    end else if (((16'd128 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd7;
    end else if (((16'd64 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd6;
    end else if (((16'd32 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd5;
    end else if (((16'd16 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd4;
    end else if (((16'd8 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd3;
    end else if (((16'd4 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd2;
    end else if (((16'd2 == AA_V_fu_380_p1) & (tmp_1_fu_414_p2 == 1'd0))) begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 4'd1;
    end else begin
        ap_phi_mux_p_s_phi_fu_159_p34 = 'bx;
    end
end

assign AA_V_fu_380_p1 = tmp_V[15:0];

assign BB_V_fu_384_p4 = {{tmp_V[31:16]}};

assign CC_V_fu_394_p4 = {{tmp_V[47:32]}};

assign DD_V_fu_404_p4 = {{tmp_V[63:48]}};

assign ap_ready = 1'b1;

assign ap_return = (tmp1_cast_fu_474_p1 + tmp_cast_fu_464_p1);

assign p_1_cast_fu_430_p1 = ap_phi_mux_p_1_phi_fu_215_p34;

assign p_2_cast_fu_440_p1 = ap_phi_mux_p_2_phi_fu_271_p34;

assign p_3_cast2_fu_450_p1 = $signed(ap_phi_mux_p_3_phi_fu_327_p34);

assign p_3_cast_fu_454_p1 = $unsigned(p_3_cast2_fu_450_p1);

assign p_cast_fu_420_p1 = ap_phi_mux_p_s_phi_fu_159_p34;

assign tmp1_cast_fu_474_p1 = tmp1_fu_468_p2;

assign tmp1_fu_468_p2 = (p_2_cast_fu_440_p1 + p_3_cast_fu_454_p1);

assign tmp_1_fu_414_p2 = ((AA_V_fu_380_p1 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_3_fu_444_p2 = ((DD_V_fu_404_p4 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_4_fu_424_p2 = ((BB_V_fu_384_p4 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_8_fu_434_p2 = ((CC_V_fu_394_p4 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_cast_fu_464_p1 = tmp_fu_458_p2;

assign tmp_fu_458_p2 = (p_1_cast_fu_430_p1 + p_cast_fu_420_p1);

endmodule //log_2_64bit
