// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _log_2_64bit_HH_
#define _log_2_64bit_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct log_2_64bit : public sc_module {
    // Port declarations 3
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<64> > tmp_V;
    sc_out< sc_lv<8> > ap_return;


    // Module declarations
    log_2_64bit(sc_module_name name);
    SC_HAS_PROCESS(log_2_64bit);

    ~log_2_64bit();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<4> > ap_phi_mux_p_s_phi_fu_159_p34;
    sc_signal< sc_lv<1> > tmp_1_fu_414_p2;
    sc_signal< sc_lv<16> > AA_V_fu_380_p1;
    sc_signal< sc_lv<5> > ap_phi_mux_p_1_phi_fu_215_p34;
    sc_signal< sc_lv<1> > tmp_4_fu_424_p2;
    sc_signal< sc_lv<16> > BB_V_fu_384_p4;
    sc_signal< sc_lv<6> > ap_phi_mux_p_2_phi_fu_271_p34;
    sc_signal< sc_lv<1> > tmp_8_fu_434_p2;
    sc_signal< sc_lv<16> > CC_V_fu_394_p4;
    sc_signal< sc_lv<5> > ap_phi_mux_p_3_phi_fu_327_p34;
    sc_signal< sc_lv<1> > tmp_3_fu_444_p2;
    sc_signal< sc_lv<16> > DD_V_fu_404_p4;
    sc_signal< sc_lv<6> > p_3_cast2_fu_450_p1;
    sc_signal< sc_lv<6> > p_1_cast_fu_430_p1;
    sc_signal< sc_lv<6> > p_cast_fu_420_p1;
    sc_signal< sc_lv<6> > tmp_fu_458_p2;
    sc_signal< sc_lv<7> > p_2_cast_fu_440_p1;
    sc_signal< sc_lv<7> > p_3_cast_fu_454_p1;
    sc_signal< sc_lv<7> > tmp1_fu_468_p2;
    sc_signal< sc_lv<8> > tmp1_cast_fu_474_p1;
    sc_signal< sc_lv<8> > tmp_cast_fu_464_p1;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<4> ap_const_lv4_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<16> ap_const_lv16_2;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<16> ap_const_lv16_4;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<16> ap_const_lv16_8;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<16> ap_const_lv16_10;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<16> ap_const_lv16_20;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<16> ap_const_lv16_40;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<16> ap_const_lv16_80;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<16> ap_const_lv16_100;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<16> ap_const_lv16_200;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<16> ap_const_lv16_400;
    static const sc_lv<4> ap_const_lv4_B;
    static const sc_lv<16> ap_const_lv16_800;
    static const sc_lv<4> ap_const_lv4_C;
    static const sc_lv<16> ap_const_lv16_1000;
    static const sc_lv<4> ap_const_lv4_D;
    static const sc_lv<16> ap_const_lv16_2000;
    static const sc_lv<4> ap_const_lv4_E;
    static const sc_lv<16> ap_const_lv16_4000;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<16> ap_const_lv16_8000;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<5> ap_const_lv5_11;
    static const sc_lv<5> ap_const_lv5_12;
    static const sc_lv<5> ap_const_lv5_13;
    static const sc_lv<5> ap_const_lv5_14;
    static const sc_lv<5> ap_const_lv5_15;
    static const sc_lv<5> ap_const_lv5_16;
    static const sc_lv<5> ap_const_lv5_17;
    static const sc_lv<5> ap_const_lv5_18;
    static const sc_lv<5> ap_const_lv5_19;
    static const sc_lv<5> ap_const_lv5_1A;
    static const sc_lv<5> ap_const_lv5_1B;
    static const sc_lv<5> ap_const_lv5_1C;
    static const sc_lv<5> ap_const_lv5_1D;
    static const sc_lv<5> ap_const_lv5_1E;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<6> ap_const_lv6_21;
    static const sc_lv<6> ap_const_lv6_22;
    static const sc_lv<6> ap_const_lv6_23;
    static const sc_lv<6> ap_const_lv6_24;
    static const sc_lv<6> ap_const_lv6_25;
    static const sc_lv<6> ap_const_lv6_26;
    static const sc_lv<6> ap_const_lv6_27;
    static const sc_lv<6> ap_const_lv6_28;
    static const sc_lv<6> ap_const_lv6_29;
    static const sc_lv<6> ap_const_lv6_2A;
    static const sc_lv<6> ap_const_lv6_2B;
    static const sc_lv<6> ap_const_lv6_2C;
    static const sc_lv<6> ap_const_lv6_2D;
    static const sc_lv<6> ap_const_lv6_2E;
    static const sc_lv<6> ap_const_lv6_2F;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_AA_V_fu_380_p1();
    void thread_BB_V_fu_384_p4();
    void thread_CC_V_fu_394_p4();
    void thread_DD_V_fu_404_p4();
    void thread_ap_phi_mux_p_1_phi_fu_215_p34();
    void thread_ap_phi_mux_p_2_phi_fu_271_p34();
    void thread_ap_phi_mux_p_3_phi_fu_327_p34();
    void thread_ap_phi_mux_p_s_phi_fu_159_p34();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_p_1_cast_fu_430_p1();
    void thread_p_2_cast_fu_440_p1();
    void thread_p_3_cast2_fu_450_p1();
    void thread_p_3_cast_fu_454_p1();
    void thread_p_cast_fu_420_p1();
    void thread_tmp1_cast_fu_474_p1();
    void thread_tmp1_fu_468_p2();
    void thread_tmp_1_fu_414_p2();
    void thread_tmp_3_fu_444_p2();
    void thread_tmp_4_fu_424_p2();
    void thread_tmp_8_fu_434_p2();
    void thread_tmp_cast_fu_464_p1();
    void thread_tmp_fu_458_p2();
};

}

using namespace ap_rtl;

#endif
