webtalk_init -webtalk_dir /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.sim/sim_1/impl/timing/xsim/xsim.dir/design_1_wrapper_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 26 23:20:18 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210387038_174145948_210294029_823" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1893319e-796d-4d1b-8ad5-20482a058896" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b9b565849b044d83ae358b796c030868" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1894.994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "54722398 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "19.49_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "174712_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2471069831 -regid "210387038_174145948_210294029_823" -xml /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.sim/sim_1/impl/timing/xsim/xsim.dir/design_1_wrapper_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.sim/sim_1/impl/timing/xsim/xsim.dir/design_1_wrapper_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.sim/sim_1/impl/timing/xsim/xsim.dir/design_1_wrapper_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
