# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xci
# IP: The module: 'design_1_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xci
# IP: The module: 'design_1_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tingyuan/Documents/SoSo/test64mau64/test64mau64.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
