// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __Ext_HTA_buddy_trebkb_H__
#define __Ext_HTA_buddy_trebkb_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct Ext_HTA_buddy_trebkb_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 64;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in <sc_lv<AddressWidth> > address1;
sc_core::sc_in <sc_logic> ce1;
sc_core::sc_out <sc_lv<DataWidth> > q1;
sc_core::sc_in<sc_logic> we1;
sc_core::sc_in<sc_lv<DataWidth> > d1;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(Ext_HTA_buddy_trebkb_ram) {
        ram[0] = "0b0000000000000000000000000000000000000000000000000000000000000000";
        ram[1] = "0b0000000000000000000000000000000000000000000000000000000000000001";
        ram[2] = "0b0000000000000000000000000000000000000000000000000000000000000011";
        ram[3] = "0b0000000000000000000000000000000000000000000000000000000000001111";
        ram[4] = "0b0000000000000000000000000000000000000000000000000000000011111111";
        ram[5] = "0b0000000000000000000000000000000000000000000000001111111111111111";
        ram[6] = "0b0000000000000000000000000000000011111111111111111111111111111111";
        for (unsigned i = 7; i < 13 ; i = i + 1) {
            ram[i] = "0b1111111111111111111111111111111111111111111111111111111111111111";
        }
        ram[13] = "0b0000000000000000000000000000000000000000000000000000000000000000";
        ram[14] = "0b0000000000000000000000000000000000000000000000000000000000000000";
        ram[15] = "0b0000000000000000000000000000000000000000000000000000000000000000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();


SC_METHOD(prc_write_1);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


void prc_write_1()
{
    if (ce1.read() == sc_dt::Log_1) 
    {
        if (we1.read() == sc_dt::Log_1) 
        {
           if(address1.read().is_01() && address1.read().to_uint()<AddressRange)
           {
              ram[address1.read().to_uint()] = d1.read(); 
              q1 = d1.read();
           }
           else
              q1 = sc_lv<DataWidth>();
        }
        else {
            if(address1.read().is_01() && address1.read().to_uint()<AddressRange)
              q1 = ram[address1.read().to_uint()];
            else
              q1 = sc_lv<DataWidth>();
        }
    }
}


}; //endmodule


SC_MODULE(Ext_HTA_buddy_trebkb) {


static const unsigned DataWidth = 64;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in <sc_lv<AddressWidth> > address1;
sc_core::sc_in<sc_logic> ce1;
sc_core::sc_out <sc_lv<DataWidth> > q1;
sc_core::sc_in<sc_logic> we1;
sc_core::sc_in<sc_lv<DataWidth> > d1;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


Ext_HTA_buddy_trebkb_ram* meminst;


SC_CTOR(Ext_HTA_buddy_trebkb) {
meminst = new Ext_HTA_buddy_trebkb_ram("Ext_HTA_buddy_trebkb_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->address1(address1);
meminst->ce1(ce1);
meminst->q1(q1);
meminst->we1(we1);
meminst->d1(d1);

meminst->reset(reset);
meminst->clk(clk);
}
~Ext_HTA_buddy_trebkb() {
    delete meminst;
}


};//endmodule
#endif
