// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="HLS_SPFA,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=3,HLS_SYN_FF=1039,HLS_SYN_LUT=1802,HLS_VERSION=2018_2}" *)

module HLS_SPFA (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        n,
        map_r_address0,
        map_r_ce0,
        map_r_q0,
        map_r_address1,
        map_r_ce1,
        map_r_q1,
        dis_output_address0,
        dis_output_ce0,
        dis_output_we0,
        dis_output_d0,
        alloc_1_size,
        alloc_1_size_ap_vld,
        alloc_1_size_ap_ack,
        alloc_1_free_target,
        alloc_1_free_target_ap_vld,
        alloc_1_free_target_ap_ack,
        alloc_1_addr,
        alloc_1_addr_ap_vld,
        alloc_1_addr_ap_ack,
        alloc_1_cmd,
        alloc_1_cmd_ap_vld,
        alloc_1_cmd_ap_ack
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] n;
output  [14:0] map_r_address0;
output   map_r_ce0;
input  [31:0] map_r_q0;
output  [14:0] map_r_address1;
output   map_r_ce1;
input  [31:0] map_r_q1;
output  [7:0] dis_output_address0;
output   dis_output_ce0;
output   dis_output_we0;
output  [31:0] dis_output_d0;
output  [31:0] alloc_1_size;
output   alloc_1_size_ap_vld;
input   alloc_1_size_ap_ack;
output  [31:0] alloc_1_free_target;
output   alloc_1_free_target_ap_vld;
input   alloc_1_free_target_ap_ack;
input  [31:0] alloc_1_addr;
input   alloc_1_addr_ap_vld;
output   alloc_1_addr_ap_ack;
output  [7:0] alloc_1_cmd;
output   alloc_1_cmd_ap_vld;
input   alloc_1_cmd_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg map_r_ce0;
reg map_r_ce1;
reg dis_output_ce0;
reg dis_output_we0;
reg[31:0] alloc_1_size;
reg alloc_1_size_ap_vld;
reg[31:0] alloc_1_free_target;
reg alloc_1_free_target_ap_vld;
reg alloc_1_addr_ap_ack;
reg[7:0] alloc_1_cmd;
reg alloc_1_cmd_ap_vld;

(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] guard_variable_for_H;
reg   [30:0] N_2;
wire   [31:0] grp_HLS_malloc_1_s_fu_521_ap_return;
reg   [31:0] reg_578;
wire    ap_CS_fsm_state18;
wire    grp_HLS_malloc_1_s_fu_521_ap_idle;
wire    grp_HLS_malloc_1_s_fu_521_ap_ready;
wire    grp_HLS_malloc_1_s_fu_521_ap_done;
wire    ap_CS_fsm_state20;
wire   [12:0] tmp_5_cast_fu_629_p3;
reg   [12:0] tmp_5_cast_reg_1349;
wire    ap_CS_fsm_state2;
reg   [10:0] p_heap0_0_addr_reg_1358;
wire   [30:0] i_4_fu_661_p2;
wire    ap_CS_fsm_state3;
wire   [30:0] i_5_fu_705_p2;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [0:0] tmp_8_fu_757_p2;
wire   [0:0] tmp_27_fu_779_p1;
reg   [0:0] tmp_27_reg_1411;
wire    ap_CS_fsm_state7;
wire  signed [31:0] now_fu_783_p3;
reg  signed [31:0] now_reg_1416;
wire   [0:0] tmp_29_fu_795_p1;
reg   [0:0] tmp_29_reg_1422;
reg   [11:0] newIndex9_reg_1427;
wire    ap_CS_fsm_state8;
wire   [12:0] tmp_26_fu_819_p1;
reg   [12:0] tmp_26_reg_1442;
wire    ap_CS_fsm_state9;
wire  signed [63:0] tmp_4_fu_823_p1;
reg  signed [63:0] tmp_4_reg_1447;
wire   [31:0] now_dis_fu_826_p3;
reg   [31:0] now_dis_reg_1452;
wire   [31:0] tmp_7_fu_833_p2;
reg   [31:0] tmp_7_reg_1458;
wire   [31:0] i_7_fu_851_p2;
reg   [31:0] i_7_reg_1467;
wire    ap_CS_fsm_state10;
wire   [11:0] tmp_32_fu_857_p1;
reg   [11:0] tmp_32_reg_1472;
wire   [0:0] tmp_10_fu_845_p2;
wire  signed [31:0] i0_fu_861_p2;
reg  signed [31:0] i0_reg_1477;
wire  signed [31:0] i1_fu_867_p2;
reg  signed [31:0] i1_reg_1484;
wire   [0:0] or_cond_fu_926_p2;
reg   [0:0] or_cond_reg_1511;
wire    ap_CS_fsm_state11;
wire   [31:0] weight0_fu_932_p2;
reg   [31:0] weight0_reg_1515;
wire   [31:0] weight1_fu_937_p2;
reg   [31:0] weight1_reg_1521;
reg   [10:0] p_heap0_0_addr_8_reg_1527;
reg   [10:0] p_heap0_1_addr_7_reg_1532;
wire   [0:0] tmp_21_fu_999_p2;
reg   [0:0] tmp_21_reg_1537;
wire    ap_CS_fsm_state12;
reg   [7:0] in_list_addr_3_reg_1543;
wire   [0:0] tmp_24_fu_1008_p2;
reg   [0:0] tmp_24_reg_1549;
reg   [7:0] in_list_addr_4_reg_1555;
wire   [31:0] weight0_heap0_load_s_fu_1013_p3;
reg   [31:0] weight0_heap0_load_s_reg_1561;
wire   [31:0] weight1_1_fu_1020_p3;
reg   [31:0] weight1_1_reg_1566;
wire   [12:0] tmp_34_fu_1027_p1;
reg   [12:0] tmp_34_reg_1571;
wire    ap_CS_fsm_state13;
wire   [0:0] brmerge3_fu_1071_p2;
reg   [0:0] brmerge3_reg_1576;
wire   [0:0] tmp_37_fu_1077_p1;
reg   [0:0] tmp_37_reg_1580;
wire   [12:0] tmp_35_fu_1103_p1;
reg   [12:0] tmp_35_reg_1590;
wire    ap_CS_fsm_state14;
wire   [0:0] tmp_36_fu_1107_p1;
reg   [0:0] tmp_36_reg_1595;
reg   [10:0] p_heap0_0_addr_9_reg_1599;
reg   [10:0] p_heap0_1_addr_8_reg_1604;
reg   [11:0] newIndex25_reg_1609;
wire    ap_CS_fsm_state15;
reg   [31:0] offset_new_node1_reg_1614;
wire    ap_CS_fsm_state16;
wire   [12:0] tmp_44_fu_1138_p1;
reg   [12:0] tmp_44_reg_1619;
wire   [0:0] tmp_45_fu_1142_p1;
reg   [0:0] tmp_45_reg_1624;
reg   [10:0] p_heap0_0_addr_15_reg_1628;
reg   [10:0] p_heap0_1_addr_14_reg_1633;
wire   [12:0] tmp_38_fu_1182_p1;
reg   [12:0] tmp_38_reg_1638;
wire   [0:0] tmp_39_fu_1186_p1;
reg   [0:0] tmp_39_reg_1643;
reg   [10:0] p_heap0_0_addr_11_reg_1647;
reg   [10:0] p_heap0_1_addr_10_reg_1652;
wire   [12:0] tmp_41_fu_1227_p1;
reg   [12:0] tmp_41_reg_1660;
wire   [0:0] tmp_42_fu_1231_p1;
reg   [0:0] tmp_42_reg_1665;
reg   [10:0] p_heap0_0_addr_13_reg_1669;
reg   [10:0] p_heap0_1_addr_12_reg_1674;
wire   [31:0] offset_next_fu_1272_p3;
wire    ap_CS_fsm_state22;
wire    grp_HLS_free_1_s_fu_538_ap_idle;
wire    grp_HLS_free_1_s_fu_538_ap_ready;
wire    grp_HLS_free_1_s_fu_538_ap_done;
wire   [30:0] i_6_fu_1288_p2;
reg   [30:0] i_6_reg_1690;
wire    ap_CS_fsm_state23;
wire   [0:0] tmp_1_fu_1283_p2;
reg   [10:0] p_heap0_0_address0;
reg    p_heap0_0_ce0;
reg    p_heap0_0_we0;
reg   [31:0] p_heap0_0_d0;
wire   [31:0] p_heap0_0_q0;
reg   [10:0] p_heap0_1_address0;
reg    p_heap0_1_ce0;
reg    p_heap0_1_we0;
reg   [31:0] p_heap0_1_d0;
wire   [31:0] p_heap0_1_q0;
reg   [7:0] in_list_address0;
reg    in_list_ce0;
reg    in_list_we0;
reg   [0:0] in_list_d0;
wire   [0:0] in_list_q0;
reg   [7:0] in_list_address1;
reg    in_list_ce1;
reg    in_list_we1;
wire   [0:0] in_list_q1;
wire    grp_HLS_malloc_1_s_fu_521_ap_start;
reg   [31:0] grp_HLS_malloc_1_s_fu_521_size;
wire   [31:0] grp_HLS_malloc_1_s_fu_521_allocator_size;
wire    grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld;
wire   [31:0] grp_HLS_malloc_1_s_fu_521_allocator_free_targe;
wire    grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld;
wire    grp_HLS_malloc_1_s_fu_521_allocator_addr_ap_ack;
wire   [7:0] grp_HLS_malloc_1_s_fu_521_allocator_cmd;
wire    grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld;
wire    grp_HLS_free_1_s_fu_538_ap_start;
wire   [31:0] grp_HLS_free_1_s_fu_538_allocator_size;
wire    grp_HLS_free_1_s_fu_538_allocator_size_ap_vld;
wire   [31:0] grp_HLS_free_1_s_fu_538_allocator_free_targe;
wire    grp_HLS_free_1_s_fu_538_allocator_free_targe_ap_vld;
wire   [7:0] grp_HLS_free_1_s_fu_538_allocator_cmd;
wire    grp_HLS_free_1_s_fu_538_allocator_cmd_ap_vld;
reg   [30:0] i_reg_466;
wire   [0:0] tmp_6_fu_656_p2;
reg   [30:0] i_1_reg_477;
wire   [0:0] tmp_9_fu_700_p2;
reg   [31:0] offset_head_reg_488;
reg   [31:0] i_2_reg_498;
wire    ap_CS_fsm_state17;
reg   [30:0] i_3_reg_509;
wire    ap_CS_fsm_state24;
reg    grp_HLS_malloc_1_s_fu_521_ap_start_reg;
wire   [0:0] brmerge4_fu_1086_p2;
wire   [0:0] brmerge5_fu_1097_p2;
reg    grp_HLS_free_1_s_fu_538_ap_start_reg;
wire   [63:0] newIndex2_fu_647_p1;
wire   [63:0] newIndex3_cast_fu_690_p1;
wire   [63:0] tmp_s_fu_711_p1;
wire   [63:0] newIndex5_fu_724_p1;
wire   [63:0] newIndex6_cast_fu_746_p1;
wire   [63:0] newIndex8_fu_773_p1;
wire   [63:0] newIndex9_cast_fu_814_p1;
wire  signed [63:0] tmp_15_fu_878_p1;
wire  signed [63:0] tmp_17_fu_888_p1;
wire   [63:0] newIndex10_cast_fu_908_p1;
wire   [63:0] newIndex11_cast_fu_964_p1;
wire   [63:0] newIndex12_cast_fu_990_p1;
wire  signed [63:0] tmp_20_fu_995_p1;
wire  signed [63:0] tmp_23_fu_1004_p1;
wire   [63:0] newIndex14_fu_1111_p1;
wire   [63:0] newIndex15_cast_fu_1117_p1;
wire   [63:0] newIndex24_fu_1146_p1;
wire   [63:0] newIndex25_cast_fu_1152_p1;
wire   [63:0] newIndex27_cast_fu_1172_p1;
wire   [63:0] newIndex17_fu_1190_p1;
wire   [63:0] newIndex18_cast_fu_1200_p1;
wire   [63:0] newIndex26_cast_fu_1221_p1;
wire    ap_CS_fsm_state19;
wire   [63:0] newIndex21_fu_1235_p1;
wire   [63:0] newIndex22_cast_fu_1245_p1;
wire   [63:0] newIndex19_cast_fu_1266_p1;
wire    ap_CS_fsm_state21;
wire   [63:0] newIndex_cast_fu_1313_p1;
wire   [63:0] tmp_11_fu_1319_p1;
wire   [0:0] guard_variable_for_H_1_load_fu_587_p1;
reg   [31:0] offset_tail_fu_90;
wire   [0:0] tmp_5_fu_671_p1;
wire   [0:0] tmp_13_fu_720_p1;
wire   [0:0] tmp_40_fu_1196_p1;
wire   [0:0] tmp_43_fu_1241_p1;
wire   [12:0] grp_fu_563_p2;
wire  signed [31:0] tmp_1_i_fu_591_p0;
wire   [31:0] tmp_1_i_fu_591_p2;
wire   [11:0] tmp_fu_619_p4;
wire   [18:0] newIndex1_fu_637_p4;
wire   [31:0] i_cast_fu_652_p1;
wire  signed [31:0] tmp_6_fu_656_p1;
wire   [12:0] tmp_3_fu_667_p1;
wire   [12:0] local_dis_0_sum2_fu_675_p2;
wire   [11:0] newIndex3_fu_680_p4;
wire   [31:0] i_1_cast_fu_696_p1;
wire  signed [31:0] tmp_9_fu_700_p1;
wire   [30:0] grp_fu_550_p4;
wire   [12:0] tmp_12_fu_716_p1;
wire   [12:0] p_sum_fu_730_p2;
wire   [11:0] newIndex6_fu_736_p4;
wire   [30:0] newIndex7_fu_763_p4;
wire   [12:0] tmp_28_fu_791_p1;
wire   [12:0] local_dis_0_sum1_fu_799_p2;
wire  signed [31:0] tmp_7_fu_833_p0;
wire  signed [31:0] extLd_fu_841_p1;
wire   [31:0] tmp_14_fu_873_p2;
wire   [31:0] tmp_16_fu_883_p2;
wire   [12:0] p_sum2_fu_893_p2;
wire   [11:0] newIndex10_fu_898_p4;
wire   [0:0] tmp_18_fu_914_p2;
wire   [0:0] tmp_19_fu_920_p2;
wire   [12:0] tmp_23_cast_fu_942_p3;
wire   [12:0] local_dis_0_sum4_fu_949_p2;
wire   [11:0] newIndex11_fu_954_p4;
wire   [12:0] tmp_26_cast_fu_969_p2;
wire   [12:0] local_dis_0_sum5_fu_975_p2;
wire   [11:0] newIndex12_fu_980_p4;
wire   [0:0] tmp_22_fu_1031_p2;
wire   [0:0] tmp_25_fu_1037_p2;
wire   [0:0] tmp7_fu_1048_p2;
wire   [0:0] tmp6_fu_1043_p2;
wire   [0:0] brmerge_demorgan_fu_1053_p2;
wire   [0:0] brmerge_demorgan_not_fu_1059_p2;
wire   [0:0] tmp8_fu_1065_p2;
wire   [0:0] tmp_24_not_fu_1081_p2;
wire   [0:0] tmp_27_not_fu_1092_p2;
wire   [11:0] grp_fu_568_p4;
wire   [12:0] p_sum3_fu_1123_p2;
wire   [12:0] p_sum4_fu_1157_p2;
wire   [11:0] newIndex27_fu_1162_p4;
wire   [12:0] p_sum6_fu_1206_p2;
wire   [11:0] newIndex26_fu_1211_p4;
wire   [12:0] p_sum8_fu_1251_p2;
wire   [11:0] newIndex19_fu_1256_p4;
wire   [31:0] i_3_cast_fu_1279_p1;
wire  signed [31:0] tmp_1_fu_1283_p1;
wire   [12:0] tmp_30_fu_1294_p1;
wire   [12:0] local_dis_0_sum_fu_1298_p2;
wire   [11:0] newIndex_fu_1303_p4;
wire   [0:0] tmp_31_fu_1324_p1;
reg   [23:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 guard_variable_for_H = 1'd0;
#0 N_2 = 31'd0;
#0 grp_HLS_malloc_1_s_fu_521_ap_start_reg = 1'b0;
#0 grp_HLS_free_1_s_fu_538_ap_start_reg = 1'b0;
end

HLS_SPFA_p_heap0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1500 ),
    .AddressWidth( 11 ))
p_heap0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_heap0_0_address0),
    .ce0(p_heap0_0_ce0),
    .we0(p_heap0_0_we0),
    .d0(p_heap0_0_d0),
    .q0(p_heap0_0_q0)
);

HLS_SPFA_p_heap0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1500 ),
    .AddressWidth( 11 ))
p_heap0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_heap0_1_address0),
    .ce0(p_heap0_1_ce0),
    .we0(p_heap0_1_we0),
    .d0(p_heap0_1_d0),
    .q0(p_heap0_1_q0)
);

HLS_SPFA_in_list #(
    .DataWidth( 1 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
in_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(in_list_address0),
    .ce0(in_list_ce0),
    .we0(in_list_we0),
    .d0(in_list_d0),
    .q0(in_list_q0),
    .address1(in_list_address1),
    .ce1(in_list_ce1),
    .we1(in_list_we1),
    .d1(1'd1),
    .q1(in_list_q1)
);

HLS_malloc_1_s grp_HLS_malloc_1_s_fu_521(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_HLS_malloc_1_s_fu_521_ap_start),
    .ap_done(grp_HLS_malloc_1_s_fu_521_ap_done),
    .ap_idle(grp_HLS_malloc_1_s_fu_521_ap_idle),
    .ap_ready(grp_HLS_malloc_1_s_fu_521_ap_ready),
    .size(grp_HLS_malloc_1_s_fu_521_size),
    .allocator_size(grp_HLS_malloc_1_s_fu_521_allocator_size),
    .allocator_size_ap_vld(grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld),
    .allocator_size_ap_ack(alloc_1_size_ap_ack),
    .allocator_free_targe(grp_HLS_malloc_1_s_fu_521_allocator_free_targe),
    .allocator_free_targe_ap_vld(grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld),
    .allocator_free_targe_ap_ack(alloc_1_free_target_ap_ack),
    .allocator_addr(alloc_1_addr),
    .allocator_addr_ap_vld(alloc_1_addr_ap_vld),
    .allocator_addr_ap_ack(grp_HLS_malloc_1_s_fu_521_allocator_addr_ap_ack),
    .allocator_cmd(grp_HLS_malloc_1_s_fu_521_allocator_cmd),
    .allocator_cmd_ap_vld(grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld),
    .allocator_cmd_ap_ack(alloc_1_cmd_ap_ack),
    .ap_return(grp_HLS_malloc_1_s_fu_521_ap_return)
);

HLS_free_1_s grp_HLS_free_1_s_fu_538(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_HLS_free_1_s_fu_538_ap_start),
    .ap_done(grp_HLS_free_1_s_fu_538_ap_done),
    .ap_idle(grp_HLS_free_1_s_fu_538_ap_idle),
    .ap_ready(grp_HLS_free_1_s_fu_538_ap_ready),
    .free_target(offset_head_reg_488),
    .allocator_size(grp_HLS_free_1_s_fu_538_allocator_size),
    .allocator_size_ap_vld(grp_HLS_free_1_s_fu_538_allocator_size_ap_vld),
    .allocator_size_ap_ack(alloc_1_size_ap_ack),
    .allocator_free_targe(grp_HLS_free_1_s_fu_538_allocator_free_targe),
    .allocator_free_targe_ap_vld(grp_HLS_free_1_s_fu_538_allocator_free_targe_ap_vld),
    .allocator_free_targe_ap_ack(alloc_1_free_target_ap_ack),
    .allocator_cmd(grp_HLS_free_1_s_fu_538_allocator_cmd),
    .allocator_cmd_ap_vld(grp_HLS_free_1_s_fu_538_allocator_cmd_ap_vld),
    .allocator_cmd_ap_ack(alloc_1_cmd_ap_ack)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_HLS_free_1_s_fu_538_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_10_fu_845_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
            grp_HLS_free_1_s_fu_538_ap_start_reg <= 1'b1;
        end else if ((grp_HLS_free_1_s_fu_538_ap_ready == 1'b1)) begin
            grp_HLS_free_1_s_fu_538_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_HLS_malloc_1_s_fu_521_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state15) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((brmerge5_fu_1097_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (brmerge4_fu_1086_p2 == 1'd1) & (brmerge3_fu_1071_p2 == 1'd1)) | ((brmerge4_fu_1086_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (brmerge3_fu_1071_p2 == 1'd1)) | ((brmerge3_fu_1071_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13)) | ((tmp_9_fu_700_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_HLS_malloc_1_s_fu_521_ap_start_reg <= 1'b1;
        end else if ((grp_HLS_malloc_1_s_fu_521_ap_ready == 1'b1)) begin
            grp_HLS_malloc_1_s_fu_521_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_9_fu_700_p2 == 1'd1))) begin
        i_1_reg_477 <= i_5_fu_705_p2;
    end else if (((tmp_6_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_1_reg_477 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        i_2_reg_498 <= i_7_reg_1467;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i_2_reg_498 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_8_fu_757_p2 == 1'd1))) begin
        i_3_reg_509 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        i_3_reg_509 <= i_6_reg_1690;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_6_fu_656_p2 == 1'd1))) begin
        i_reg_466 <= i_4_fu_661_p2;
    end else if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_466 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_HLS_free_1_s_fu_538_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        offset_head_reg_488 <= offset_next_fu_1272_p3;
    end else if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        offset_head_reg_488 <= grp_HLS_malloc_1_s_fu_521_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19))) begin
        offset_tail_fu_90 <= reg_578;
    end else if (((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        offset_tail_fu_90 <= offset_new_node1_reg_1614;
    end else if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        offset_tail_fu_90 <= grp_HLS_malloc_1_s_fu_521_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((guard_variable_for_H_1_load_fu_587_p1 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        N_2 <= {{tmp_1_i_fu_591_p2[31:1]}};
        guard_variable_for_H <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        brmerge3_reg_1576 <= brmerge3_fu_1071_p2;
        tmp_34_reg_1571 <= tmp_34_fu_1027_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (tmp_10_fu_845_p2 == 1'd1))) begin
        i0_reg_1477[31 : 1] <= i0_fu_861_p2[31 : 1];
        i1_reg_1484[31 : 1] <= i1_fu_867_p2[31 : 1];
        tmp_32_reg_1472 <= tmp_32_fu_857_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        i_6_reg_1690 <= i_6_fu_1288_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_7_reg_1467 <= i_7_fu_851_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        in_list_addr_3_reg_1543[7 : 1] <= tmp_20_fu_995_p1[7 : 1];
        in_list_addr_4_reg_1555[7 : 1] <= tmp_23_fu_1004_p1[7 : 1];
        tmp_21_reg_1537 <= tmp_21_fu_999_p2;
        tmp_24_reg_1549 <= tmp_24_fu_1008_p2;
        weight0_heap0_load_s_reg_1561 <= weight0_heap0_load_s_fu_1013_p3;
        weight1_1_reg_1566 <= weight1_1_fu_1020_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        newIndex25_reg_1609 <= {{p_sum3_fu_1123_p2[12:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        newIndex9_reg_1427 <= {{local_dis_0_sum1_fu_799_p2[12:1]}};
        now_reg_1416 <= now_fu_783_p3;
        tmp_27_reg_1411 <= tmp_27_fu_779_p1;
        tmp_29_reg_1422 <= tmp_29_fu_795_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        now_dis_reg_1452 <= now_dis_fu_826_p3;
        tmp_26_reg_1442 <= tmp_26_fu_819_p1;
        tmp_4_reg_1447 <= tmp_4_fu_823_p1;
        tmp_7_reg_1458 <= tmp_7_fu_833_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        offset_new_node1_reg_1614 <= grp_HLS_malloc_1_s_fu_521_ap_return;
        p_heap0_0_addr_15_reg_1628 <= newIndex24_fu_1146_p1;
        p_heap0_1_addr_14_reg_1633 <= newIndex24_fu_1146_p1;
        tmp_44_reg_1619 <= tmp_44_fu_1138_p1;
        tmp_45_reg_1624 <= tmp_45_fu_1142_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        or_cond_reg_1511 <= or_cond_fu_926_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        p_heap0_0_addr_11_reg_1647 <= newIndex17_fu_1190_p1;
        p_heap0_1_addr_10_reg_1652 <= newIndex17_fu_1190_p1;
        tmp_38_reg_1638 <= tmp_38_fu_1182_p1;
        tmp_39_reg_1643 <= tmp_39_fu_1186_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        p_heap0_0_addr_13_reg_1669 <= newIndex21_fu_1235_p1;
        p_heap0_1_addr_12_reg_1674 <= newIndex21_fu_1235_p1;
        tmp_41_reg_1660 <= tmp_41_fu_1227_p1;
        tmp_42_reg_1665 <= tmp_42_fu_1231_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_926_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        p_heap0_0_addr_8_reg_1527 <= newIndex11_cast_fu_964_p1;
        p_heap0_1_addr_7_reg_1532 <= newIndex12_cast_fu_990_p1;
        weight0_reg_1515 <= weight0_fu_932_p2;
        weight1_reg_1521 <= weight1_fu_937_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        p_heap0_0_addr_9_reg_1599 <= newIndex14_fu_1111_p1;
        p_heap0_1_addr_8_reg_1604 <= newIndex14_fu_1111_p1;
        tmp_35_reg_1590 <= tmp_35_fu_1103_p1;
        tmp_36_reg_1595 <= tmp_36_fu_1107_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_heap0_0_addr_reg_1358 <= newIndex2_fu_647_p1;
        tmp_5_cast_reg_1349[12 : 1] <= tmp_5_cast_fu_629_p3[12 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        reg_578 <= grp_HLS_malloc_1_s_fu_521_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((brmerge3_fu_1071_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        tmp_37_reg_1580 <= tmp_37_fu_1077_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        alloc_1_addr_ap_ack = grp_HLS_malloc_1_s_fu_521_allocator_addr_ap_ack;
    end else begin
        alloc_1_addr_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HLS_free_1_s_fu_538_allocator_cmd_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        alloc_1_cmd = grp_HLS_free_1_s_fu_538_allocator_cmd;
    end else if ((((1'b1 == ap_CS_fsm_state20) & (grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state18) & (grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld == 1'b1)) | ((grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        alloc_1_cmd = grp_HLS_malloc_1_s_fu_521_allocator_cmd;
    end else begin
        alloc_1_cmd = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        alloc_1_cmd_ap_vld = grp_HLS_free_1_s_fu_538_allocator_cmd_ap_vld;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        alloc_1_cmd_ap_vld = grp_HLS_malloc_1_s_fu_521_allocator_cmd_ap_vld;
    end else begin
        alloc_1_cmd_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HLS_free_1_s_fu_538_allocator_free_targe_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        alloc_1_free_target = grp_HLS_free_1_s_fu_538_allocator_free_targe;
    end else if ((((1'b1 == ap_CS_fsm_state20) & (grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state18) & (grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld == 1'b1)) | ((grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        alloc_1_free_target = grp_HLS_malloc_1_s_fu_521_allocator_free_targe;
    end else begin
        alloc_1_free_target = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        alloc_1_free_target_ap_vld = grp_HLS_free_1_s_fu_538_allocator_free_targe_ap_vld;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        alloc_1_free_target_ap_vld = grp_HLS_malloc_1_s_fu_521_allocator_free_targe_ap_vld;
    end else begin
        alloc_1_free_target_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HLS_free_1_s_fu_538_allocator_size_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        alloc_1_size = grp_HLS_free_1_s_fu_538_allocator_size;
    end else if ((((1'b1 == ap_CS_fsm_state20) & (grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state18) & (grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld == 1'b1)) | ((grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        alloc_1_size = grp_HLS_malloc_1_s_fu_521_allocator_size;
    end else begin
        alloc_1_size = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        alloc_1_size_ap_vld = grp_HLS_free_1_s_fu_538_allocator_size_ap_vld;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        alloc_1_size_ap_vld = grp_HLS_malloc_1_s_fu_521_allocator_size_ap_vld;
    end else begin
        alloc_1_size_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_fu_1283_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_fu_1283_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        dis_output_ce0 = 1'b1;
    end else begin
        dis_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        dis_output_we0 = 1'b1;
    end else begin
        dis_output_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_HLS_malloc_1_s_fu_521_size = 32'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_HLS_malloc_1_s_fu_521_size = n;
    end else begin
        grp_HLS_malloc_1_s_fu_521_size = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        in_list_address0 = in_list_addr_4_reg_1555;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_list_address0 = tmp_20_fu_995_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_list_address0 = tmp_4_reg_1447;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        in_list_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_list_address0 = tmp_s_fu_711_p1;
    end else begin
        in_list_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        in_list_address1 = in_list_addr_4_reg_1555;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17))) begin
        in_list_address1 = in_list_addr_3_reg_1543;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_list_address1 = tmp_23_fu_1004_p1;
    end else begin
        in_list_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state4) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        in_list_ce0 = 1'b1;
    end else begin
        in_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12))) begin
        in_list_ce1 = 1'b1;
    end else begin
        in_list_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state5))) begin
        in_list_d0 = 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state4))) begin
        in_list_d0 = 1'd0;
    end else begin
        in_list_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17)) | ((tmp_10_fu_845_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10)) | ((1'b1 == ap_CS_fsm_state4) & (tmp_9_fu_700_p2 == 1'd1)))) begin
        in_list_we0 = 1'b1;
    end else begin
        in_list_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | ((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17)))) begin
        in_list_we1 = 1'b1;
    end else begin
        in_list_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        map_r_ce0 = 1'b1;
    end else begin
        map_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        map_r_ce1 = 1'b1;
    end else begin
        map_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        p_heap0_0_address0 = newIndex_cast_fu_1313_p1;
    end else if (((1'b1 == ap_CS_fsm_state21) & (tmp_42_reg_1665 == 1'd1))) begin
        p_heap0_0_address0 = newIndex19_cast_fu_1266_p1;
    end else if (((tmp_42_reg_1665 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        p_heap0_0_address0 = p_heap0_0_addr_13_reg_1669;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        p_heap0_0_address0 = newIndex22_cast_fu_1245_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) & (tmp_39_reg_1643 == 1'd1))) begin
        p_heap0_0_address0 = newIndex26_cast_fu_1221_p1;
    end else if (((tmp_39_reg_1643 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        p_heap0_0_address0 = p_heap0_0_addr_11_reg_1647;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        p_heap0_0_address0 = newIndex18_cast_fu_1200_p1;
    end else if (((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (tmp_45_reg_1624 == 1'd1))) begin
        p_heap0_0_address0 = newIndex27_cast_fu_1172_p1;
    end else if (((tmp_45_reg_1624 == 1'd0) & (brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        p_heap0_0_address0 = p_heap0_0_addr_15_reg_1628;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        p_heap0_0_address0 = newIndex25_cast_fu_1152_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        p_heap0_0_address0 = p_heap0_0_addr_9_reg_1599;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        p_heap0_0_address0 = newIndex15_cast_fu_1117_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        p_heap0_0_address0 = p_heap0_0_addr_8_reg_1527;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        p_heap0_0_address0 = newIndex11_cast_fu_964_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_heap0_0_address0 = newIndex10_cast_fu_908_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_heap0_0_address0 = newIndex9_cast_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_heap0_0_address0 = newIndex8_fu_773_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (tmp_13_fu_720_p1 == 1'd1))) begin
        p_heap0_0_address0 = newIndex6_cast_fu_746_p1;
    end else if (((tmp_13_fu_720_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        p_heap0_0_address0 = newIndex5_fu_724_p1;
    end else if (((tmp_6_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        p_heap0_0_address0 = p_heap0_0_addr_reg_1358;
    end else if (((tmp_5_fu_671_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (tmp_6_fu_656_p2 == 1'd1))) begin
        p_heap0_0_address0 = newIndex3_cast_fu_690_p1;
    end else begin
        p_heap0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (tmp_13_fu_720_p1 == 1'd1)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (tmp_13_fu_720_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((1'b1 == ap_CS_fsm_state21) & (tmp_42_reg_1665 == 1'd1)) | ((tmp_42_reg_1665 == 1'd0) & (1'b1 == ap_CS_fsm_state21)) | ((1'b1 == ap_CS_fsm_state19) & (tmp_39_reg_1643 == 1'd1)) | ((tmp_39_reg_1643 == 1'd0) & (1'b1 == ap_CS_fsm_state19)) | ((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (tmp_45_reg_1624 == 1'd1)) | ((tmp_45_reg_1624 == 1'd0) & (brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17)) | ((tmp_6_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((tmp_5_fu_671_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (tmp_6_fu_656_p2 == 1'd1)))) begin
        p_heap0_0_ce0 = 1'b1;
    end else begin
        p_heap0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_42_reg_1665 == 1'd0) & (1'b1 == ap_CS_fsm_state21)) | ((tmp_45_reg_1624 == 1'd0) & (brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17)))) begin
        p_heap0_0_d0 = i1_reg_1484;
    end else if (((1'b1 == ap_CS_fsm_state15) | ((tmp_39_reg_1643 == 1'd0) & (1'b1 == ap_CS_fsm_state19)))) begin
        p_heap0_0_d0 = i0_reg_1477;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14))) begin
        p_heap0_0_d0 = grp_HLS_malloc_1_s_fu_521_ap_return;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        p_heap0_0_d0 = weight0_heap0_load_s_reg_1561;
    end else if ((((1'b1 == ap_CS_fsm_state21) & (tmp_42_reg_1665 == 1'd1)) | ((1'b1 == ap_CS_fsm_state19) & (tmp_39_reg_1643 == 1'd1)) | ((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (tmp_45_reg_1624 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (tmp_13_fu_720_p1 == 1'd1)))) begin
        p_heap0_0_d0 = 32'd4294967295;
    end else if ((((tmp_13_fu_720_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_6_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        p_heap0_0_d0 = 32'd0;
    end else if (((tmp_5_fu_671_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (tmp_6_fu_656_p2 == 1'd1))) begin
        p_heap0_0_d0 = 32'd10000;
    end else begin
        p_heap0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20) & (tmp_43_fu_1241_p1 == 1'd1)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16) & (tmp_36_reg_1595 == 1'd1)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14) & (tmp_37_reg_1580 == 1'd1)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (tmp_13_fu_720_p1 == 1'd1)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (tmp_13_fu_720_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18) & (tmp_40_fu_1196_p1 == 1'd1)) | ((1'b1 == ap_CS_fsm_state21) & (tmp_42_reg_1665 == 1'd1)) | ((tmp_42_reg_1665 == 1'd0) & (1'b1 == ap_CS_fsm_state21)) | ((1'b1 == ap_CS_fsm_state19) & (tmp_39_reg_1643 == 1'd1)) | ((tmp_39_reg_1643 == 1'd0) & (1'b1 == ap_CS_fsm_state19)) | ((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (tmp_45_reg_1624 == 1'd1)) | ((tmp_45_reg_1624 == 1'd0) & (brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17)) | ((tmp_36_reg_1595 == 1'd0) & (1'b1 == ap_CS_fsm_state15)) | ((tmp_6_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((tmp_5_fu_671_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (tmp_6_fu_656_p2 == 1'd1)))) begin
        p_heap0_0_we0 = 1'b1;
    end else begin
        p_heap0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        p_heap0_1_address0 = newIndex_cast_fu_1313_p1;
    end else if (((tmp_42_reg_1665 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        p_heap0_1_address0 = newIndex19_cast_fu_1266_p1;
    end else if (((1'b1 == ap_CS_fsm_state21) & (tmp_42_reg_1665 == 1'd1))) begin
        p_heap0_1_address0 = p_heap0_1_addr_12_reg_1674;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        p_heap0_1_address0 = newIndex22_cast_fu_1245_p1;
    end else if (((tmp_39_reg_1643 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        p_heap0_1_address0 = newIndex26_cast_fu_1221_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) & (tmp_39_reg_1643 == 1'd1))) begin
        p_heap0_1_address0 = p_heap0_1_addr_10_reg_1652;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        p_heap0_1_address0 = newIndex18_cast_fu_1200_p1;
    end else if (((tmp_45_reg_1624 == 1'd0) & (brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        p_heap0_1_address0 = newIndex27_cast_fu_1172_p1;
    end else if (((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (tmp_45_reg_1624 == 1'd1))) begin
        p_heap0_1_address0 = p_heap0_1_addr_14_reg_1633;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        p_heap0_1_address0 = newIndex25_cast_fu_1152_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        p_heap0_1_address0 = p_heap0_1_addr_8_reg_1604;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        p_heap0_1_address0 = newIndex15_cast_fu_1117_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        p_heap0_1_address0 = p_heap0_1_addr_7_reg_1532;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        p_heap0_1_address0 = newIndex12_cast_fu_990_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_heap0_1_address0 = newIndex10_cast_fu_908_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_heap0_1_address0 = newIndex9_cast_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_heap0_1_address0 = newIndex8_fu_773_p1;
    end else if (((tmp_13_fu_720_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        p_heap0_1_address0 = newIndex6_cast_fu_746_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (tmp_13_fu_720_p1 == 1'd1))) begin
        p_heap0_1_address0 = newIndex5_fu_724_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_heap0_1_address0 = newIndex3_cast_fu_690_p1;
    end else begin
        p_heap0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state3) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (tmp_13_fu_720_p1 == 1'd1)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (tmp_13_fu_720_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((1'b1 == ap_CS_fsm_state21) & (tmp_42_reg_1665 == 1'd1)) | ((tmp_42_reg_1665 == 1'd0) & (1'b1 == ap_CS_fsm_state21)) | ((1'b1 == ap_CS_fsm_state19) & (tmp_39_reg_1643 == 1'd1)) | ((tmp_39_reg_1643 == 1'd0) & (1'b1 == ap_CS_fsm_state19)) | ((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (tmp_45_reg_1624 == 1'd1)) | ((tmp_45_reg_1624 == 1'd0) & (brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17)))) begin
        p_heap0_1_ce0 = 1'b1;
    end else begin
        p_heap0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state21) & (tmp_42_reg_1665 == 1'd1)) | ((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (tmp_45_reg_1624 == 1'd1)))) begin
        p_heap0_1_d0 = i1_reg_1484;
    end else if (((1'b1 == ap_CS_fsm_state15) | ((1'b1 == ap_CS_fsm_state19) & (tmp_39_reg_1643 == 1'd1)))) begin
        p_heap0_1_d0 = i0_reg_1477;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14))) begin
        p_heap0_1_d0 = grp_HLS_malloc_1_s_fu_521_ap_return;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        p_heap0_1_d0 = weight1_1_reg_1566;
    end else if ((((tmp_42_reg_1665 == 1'd0) & (1'b1 == ap_CS_fsm_state21)) | ((tmp_39_reg_1643 == 1'd0) & (1'b1 == ap_CS_fsm_state19)) | ((tmp_45_reg_1624 == 1'd0) & (brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17)) | ((tmp_13_fu_720_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        p_heap0_1_d0 = 32'd4294967295;
    end else if (((1'b1 == ap_CS_fsm_state5) & (tmp_13_fu_720_p1 == 1'd1))) begin
        p_heap0_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_heap0_1_d0 = 32'd10000;
    end else begin
        p_heap0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (tmp_43_fu_1241_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state20)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (tmp_36_reg_1595 == 1'd0) & (1'b1 == ap_CS_fsm_state16)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (tmp_37_reg_1580 == 1'd0) & (1'b1 == ap_CS_fsm_state14)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (tmp_13_fu_720_p1 == 1'd1)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (tmp_13_fu_720_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (tmp_40_fu_1196_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state18)) | ((1'b1 == ap_CS_fsm_state21) & (tmp_42_reg_1665 == 1'd1)) | ((tmp_42_reg_1665 == 1'd0) & (1'b1 == ap_CS_fsm_state21)) | ((1'b1 == ap_CS_fsm_state19) & (tmp_39_reg_1643 == 1'd1)) | ((tmp_39_reg_1643 == 1'd0) & (1'b1 == ap_CS_fsm_state19)) | ((brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (tmp_45_reg_1624 == 1'd1)) | ((tmp_45_reg_1624 == 1'd0) & (brmerge3_reg_1576 == 1'd0) & (or_cond_reg_1511 == 1'd0) & (1'b1 == ap_CS_fsm_state17)) | ((1'b1 == ap_CS_fsm_state15) & (tmp_36_reg_1595 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (tmp_5_fu_671_p1 == 1'd1) & (tmp_6_fu_656_p2 == 1'd1)))) begin
        p_heap0_1_we0 = 1'b1;
    end else begin
        p_heap0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_6_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (tmp_9_fu_700_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (tmp_8_fu_757_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((tmp_10_fu_845_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (or_cond_fu_926_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((brmerge5_fu_1097_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (brmerge4_fu_1086_p2 == 1'd1) & (brmerge3_fu_1071_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else if (((1'b1 == ap_CS_fsm_state13) & (brmerge5_fu_1097_p2 == 1'd1) & (brmerge4_fu_1086_p2 == 1'd1) & (brmerge3_fu_1071_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((brmerge4_fu_1086_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (brmerge3_fu_1071_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_HLS_malloc_1_s_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state22 : begin
            if (((grp_HLS_free_1_s_fu_538_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((tmp_1_fu_1283_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign brmerge3_fu_1071_p2 = (tmp8_fu_1065_p2 | in_list_q0);

assign brmerge4_fu_1086_p2 = (tmp_24_not_fu_1081_p2 | in_list_q0);

assign brmerge5_fu_1097_p2 = (tmp_27_not_fu_1092_p2 | in_list_q1);

assign brmerge_demorgan_fu_1053_p2 = (tmp7_fu_1048_p2 & tmp6_fu_1043_p2);

assign brmerge_demorgan_not_fu_1059_p2 = (brmerge_demorgan_fu_1053_p2 ^ 1'd1);

assign dis_output_address0 = tmp_11_fu_1319_p1;

assign dis_output_d0 = ((tmp_31_fu_1324_p1[0:0] === 1'b1) ? p_heap0_1_q0 : p_heap0_0_q0);

assign extLd_fu_841_p1 = $signed(N_2);

assign grp_HLS_free_1_s_fu_538_ap_start = grp_HLS_free_1_s_fu_538_ap_start_reg;

assign grp_HLS_malloc_1_s_fu_521_ap_start = grp_HLS_malloc_1_s_fu_521_ap_start_reg;

assign grp_fu_550_p4 = {{grp_HLS_malloc_1_s_fu_521_ap_return[31:1]}};

assign grp_fu_563_p2 = (13'd1 + tmp_34_reg_1571);

assign grp_fu_568_p4 = {{grp_fu_563_p2[12:1]}};

assign guard_variable_for_H_1_load_fu_587_p1 = guard_variable_for_H;

assign i0_fu_861_p2 = i_2_reg_498 << 32'd1;

assign i1_fu_867_p2 = (i0_fu_861_p2 | 32'd1);

assign i_1_cast_fu_696_p1 = i_1_reg_477;

assign i_3_cast_fu_1279_p1 = i_3_reg_509;

assign i_4_fu_661_p2 = (i_reg_466 + 31'd1);

assign i_5_fu_705_p2 = (i_1_reg_477 + 31'd1);

assign i_6_fu_1288_p2 = (i_3_reg_509 + 31'd1);

assign i_7_fu_851_p2 = (i_2_reg_498 + 32'd1);

assign i_cast_fu_652_p1 = i_reg_466;

assign local_dis_0_sum1_fu_799_p2 = (tmp_5_cast_reg_1349 + tmp_28_fu_791_p1);

assign local_dis_0_sum2_fu_675_p2 = (tmp_3_fu_667_p1 + tmp_5_cast_reg_1349);

assign local_dis_0_sum4_fu_949_p2 = (tmp_5_cast_reg_1349 + tmp_23_cast_fu_942_p3);

assign local_dis_0_sum5_fu_975_p2 = (tmp_5_cast_reg_1349 + tmp_26_cast_fu_969_p2);

assign local_dis_0_sum_fu_1298_p2 = (tmp_30_fu_1294_p1 + tmp_5_cast_reg_1349);

assign map_r_address0 = tmp_15_fu_878_p1;

assign map_r_address1 = tmp_17_fu_888_p1;

assign newIndex10_cast_fu_908_p1 = newIndex10_fu_898_p4;

assign newIndex10_fu_898_p4 = {{p_sum2_fu_893_p2[12:1]}};

assign newIndex11_cast_fu_964_p1 = newIndex11_fu_954_p4;

assign newIndex11_fu_954_p4 = {{local_dis_0_sum4_fu_949_p2[12:1]}};

assign newIndex12_cast_fu_990_p1 = newIndex12_fu_980_p4;

assign newIndex12_fu_980_p4 = {{local_dis_0_sum5_fu_975_p2[12:1]}};

assign newIndex14_fu_1111_p1 = grp_fu_550_p4;

assign newIndex15_cast_fu_1117_p1 = grp_fu_568_p4;

assign newIndex17_fu_1190_p1 = grp_fu_550_p4;

assign newIndex18_cast_fu_1200_p1 = grp_fu_568_p4;

assign newIndex19_cast_fu_1266_p1 = newIndex19_fu_1256_p4;

assign newIndex19_fu_1256_p4 = {{p_sum8_fu_1251_p2[12:1]}};

assign newIndex1_fu_637_p4 = {{grp_HLS_malloc_1_s_fu_521_ap_return[19:1]}};

assign newIndex21_fu_1235_p1 = grp_fu_550_p4;

assign newIndex22_cast_fu_1245_p1 = grp_fu_568_p4;

assign newIndex24_fu_1146_p1 = grp_fu_550_p4;

assign newIndex25_cast_fu_1152_p1 = newIndex25_reg_1609;

assign newIndex26_cast_fu_1221_p1 = newIndex26_fu_1211_p4;

assign newIndex26_fu_1211_p4 = {{p_sum6_fu_1206_p2[12:1]}};

assign newIndex27_cast_fu_1172_p1 = newIndex27_fu_1162_p4;

assign newIndex27_fu_1162_p4 = {{p_sum4_fu_1157_p2[12:1]}};

assign newIndex2_fu_647_p1 = newIndex1_fu_637_p4;

assign newIndex3_cast_fu_690_p1 = newIndex3_fu_680_p4;

assign newIndex3_fu_680_p4 = {{local_dis_0_sum2_fu_675_p2[12:1]}};

assign newIndex5_fu_724_p1 = grp_fu_550_p4;

assign newIndex6_cast_fu_746_p1 = newIndex6_fu_736_p4;

assign newIndex6_fu_736_p4 = {{p_sum_fu_730_p2[12:1]}};

assign newIndex7_fu_763_p4 = {{offset_head_reg_488[31:1]}};

assign newIndex8_fu_773_p1 = newIndex7_fu_763_p4;

assign newIndex9_cast_fu_814_p1 = newIndex9_reg_1427;

assign newIndex_cast_fu_1313_p1 = newIndex_fu_1303_p4;

assign newIndex_fu_1303_p4 = {{local_dis_0_sum_fu_1298_p2[12:1]}};

assign now_dis_fu_826_p3 = ((tmp_29_reg_1422[0:0] === 1'b1) ? p_heap0_1_q0 : p_heap0_0_q0);

assign now_fu_783_p3 = ((tmp_27_fu_779_p1[0:0] === 1'b1) ? p_heap0_1_q0 : p_heap0_0_q0);

assign offset_next_fu_1272_p3 = ((tmp_27_reg_1411[0:0] === 1'b1) ? p_heap0_0_q0 : p_heap0_1_q0);

assign or_cond_fu_926_p2 = (tmp_19_fu_920_p2 & tmp_18_fu_914_p2);

assign p_sum2_fu_893_p2 = (tmp_26_reg_1442 + 13'd1);

assign p_sum3_fu_1123_p2 = (13'd1 + tmp_35_reg_1590);

assign p_sum4_fu_1157_p2 = (tmp_44_reg_1619 + 13'd1);

assign p_sum6_fu_1206_p2 = (tmp_38_reg_1638 + 13'd1);

assign p_sum8_fu_1251_p2 = (tmp_41_reg_1660 + 13'd1);

assign p_sum_fu_730_p2 = (tmp_12_fu_716_p1 + 13'd1);

assign tmp6_fu_1043_p2 = (tmp_22_fu_1031_p2 & tmp_21_reg_1537);

assign tmp7_fu_1048_p2 = (tmp_25_fu_1037_p2 & tmp_24_reg_1549);

assign tmp8_fu_1065_p2 = (in_list_q1 | brmerge_demorgan_not_fu_1059_p2);

assign tmp_10_fu_845_p2 = (($signed(i_2_reg_498) < $signed(extLd_fu_841_p1)) ? 1'b1 : 1'b0);

assign tmp_11_fu_1319_p1 = i_3_reg_509;

assign tmp_12_fu_716_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[12:0];

assign tmp_13_fu_720_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[0:0];

assign tmp_14_fu_873_p2 = ($signed(tmp_7_reg_1458) + $signed(i0_fu_861_p2));

assign tmp_15_fu_878_p1 = $signed(tmp_14_fu_873_p2);

assign tmp_16_fu_883_p2 = ($signed(tmp_7_reg_1458) + $signed(i1_fu_867_p2));

assign tmp_17_fu_888_p1 = $signed(tmp_16_fu_883_p2);

assign tmp_18_fu_914_p2 = (($signed(map_r_q0) > $signed(32'd9999)) ? 1'b1 : 1'b0);

assign tmp_19_fu_920_p2 = (($signed(map_r_q1) > $signed(32'd9999)) ? 1'b1 : 1'b0);

assign tmp_1_fu_1283_p1 = n;

assign tmp_1_fu_1283_p2 = (($signed(i_3_cast_fu_1279_p1) < $signed(tmp_1_fu_1283_p1)) ? 1'b1 : 1'b0);

assign tmp_1_i_fu_591_p0 = n;

assign tmp_1_i_fu_591_p2 = ($signed(tmp_1_i_fu_591_p0) + $signed(32'd1));

assign tmp_20_fu_995_p1 = i0_reg_1477;

assign tmp_21_fu_999_p2 = (($signed(weight0_reg_1515) < $signed(p_heap0_0_q0)) ? 1'b1 : 1'b0);

assign tmp_22_fu_1031_p2 = (in_list_q0 ^ 1'd1);

assign tmp_23_cast_fu_942_p3 = {{tmp_32_reg_1472}, {1'd0}};

assign tmp_23_fu_1004_p1 = i1_reg_1484;

assign tmp_24_fu_1008_p2 = (($signed(weight1_reg_1521) < $signed(p_heap0_1_q0)) ? 1'b1 : 1'b0);

assign tmp_24_not_fu_1081_p2 = (tmp_21_reg_1537 ^ 1'd1);

assign tmp_25_fu_1037_p2 = (in_list_q1 ^ 1'd1);

assign tmp_26_cast_fu_969_p2 = (tmp_23_cast_fu_942_p3 | 13'd1);

assign tmp_26_fu_819_p1 = offset_head_reg_488[12:0];

assign tmp_27_fu_779_p1 = offset_head_reg_488[0:0];

assign tmp_27_not_fu_1092_p2 = (tmp_24_reg_1549 ^ 1'd1);

assign tmp_28_fu_791_p1 = now_fu_783_p3[12:0];

assign tmp_29_fu_795_p1 = now_fu_783_p3[0:0];

assign tmp_30_fu_1294_p1 = i_3_reg_509[12:0];

assign tmp_31_fu_1324_p1 = i_3_reg_509[0:0];

assign tmp_32_fu_857_p1 = i_2_reg_498[11:0];

assign tmp_34_fu_1027_p1 = offset_tail_fu_90[12:0];

assign tmp_35_fu_1103_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[12:0];

assign tmp_36_fu_1107_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[0:0];

assign tmp_37_fu_1077_p1 = offset_tail_fu_90[0:0];

assign tmp_38_fu_1182_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[12:0];

assign tmp_39_fu_1186_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[0:0];

assign tmp_3_fu_667_p1 = i_reg_466[12:0];

assign tmp_40_fu_1196_p1 = offset_tail_fu_90[0:0];

assign tmp_41_fu_1227_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[12:0];

assign tmp_42_fu_1231_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[0:0];

assign tmp_43_fu_1241_p1 = offset_tail_fu_90[0:0];

assign tmp_44_fu_1138_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[12:0];

assign tmp_45_fu_1142_p1 = grp_HLS_malloc_1_s_fu_521_ap_return[0:0];

assign tmp_4_fu_823_p1 = now_reg_1416;

assign tmp_5_cast_fu_629_p3 = {{tmp_fu_619_p4}, {1'd0}};

assign tmp_5_fu_671_p1 = i_reg_466[0:0];

assign tmp_6_fu_656_p1 = n;

assign tmp_6_fu_656_p2 = (($signed(i_cast_fu_652_p1) < $signed(tmp_6_fu_656_p1)) ? 1'b1 : 1'b0);

assign tmp_7_fu_833_p0 = n;

assign tmp_7_fu_833_p2 = ($signed(tmp_7_fu_833_p0) * $signed(now_reg_1416));

assign tmp_8_fu_757_p2 = ((offset_head_reg_488 == 32'd4294967295) ? 1'b1 : 1'b0);

assign tmp_9_fu_700_p1 = n;

assign tmp_9_fu_700_p2 = (($signed(i_1_cast_fu_696_p1) < $signed(tmp_9_fu_700_p1)) ? 1'b1 : 1'b0);

assign tmp_fu_619_p4 = {{grp_HLS_malloc_1_s_fu_521_ap_return[12:1]}};

assign tmp_s_fu_711_p1 = i_1_reg_477;

assign weight0_fu_932_p2 = (now_dis_reg_1452 + map_r_q0);

assign weight0_heap0_load_s_fu_1013_p3 = ((tmp_21_fu_999_p2[0:0] === 1'b1) ? weight0_reg_1515 : p_heap0_0_q0);

assign weight1_1_fu_1020_p3 = ((tmp_24_fu_1008_p2[0:0] === 1'b1) ? weight1_reg_1521 : p_heap0_1_q0);

assign weight1_fu_937_p2 = (now_dis_reg_1452 + map_r_q1);

always @ (posedge ap_clk) begin
    tmp_5_cast_reg_1349[0] <= 1'b0;
    i0_reg_1477[0] <= 1'b0;
    i1_reg_1484[0] <= 1'b1;
    in_list_addr_3_reg_1543[0] <= 1'b0;
    in_list_addr_4_reg_1555[0] <= 1'b1;
end

endmodule //HLS_SPFA
